/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
  }
  plugins {
    kotlin("multiplatform") version "1.9.24"
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
  }
}

dependencyResolutionManagement { repositories { mavenCentral() } }

rootProject.name = "mp_playground"

include(":app", ":lib")
