/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import utils1.*;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public int add(int a, int b) {
    return a + b;
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    // System.out.println(UtilsImpl2.add(1, 2));
    System.out.println(Utils.add(1, 2));
  }
}
