/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    assertEquals(10, classUnderTest.add(2, 8), "2 + 8 = 11.");
  }
}
