/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("multiplatform")
}

repositories {
    mavenCentral()
}

kotlin {
    macosArm64("native") {
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }
    
    // sourceSets {
    //     val macosArm64Main by getting {
    //         dependencies {
    //             implementation(kotlin("stdlib"))
    //         }
    //     }
    //     val macosArm64Test by getting {
    //         dependencies {
    //             implementation(kotlin("test"))
    //         }
    //     }
    // }
}
